### ISSUE TITLE
Please fix version in Android APK

### ISSUE THREAD

**Issue by IzzySoft** [Superredstone/Port-Scanner#1]
I just downloaded the APK vrom the latest tag (v1.2.0) and noticed it identifies as v1.0.1, versionCode 1

    package: name='com.portscanner.superredstone' versionCode='1' versionName='1.0.1'

I had expected finding it as `versionCode='3' versionName='1.2.0' – as there already were 2 releases before it and the tag name indicates 1.2.0. While the latter (1.0.1) might be a cosmetic thing (but making it hard for you to tell which version was really used when you get bug reports), not increasing `versionCode` with each release is rather critical, as that's what Android uses to tell versions apart. So if `1` is already installed, it's not considered an update and thus not offered as such.

Also it makes it hard to check for update: If the app tells me I have v1.0.1 installed and I need to remember this in fact is v1.2.0, I'll always be confused :wink:

So **TL;DR:** could you please keep versions updated with the APKs? Else you'll also have a problem with [your F-Droid listing](https://gitlab.com/fdroid/rfp/-/issues/1766) which cannot be processed, as it requires tag name to be in sync with `versionName` – and of course `versionCode` increased with each new release. Thanks!

**Comment by Superredstone** [comment]
Thanks for the report

**Comment by IzzySoft** [comment]
Thanks! Until your app is up at F-Droid, could you please attach the APK to the latest release (and future ones) again? In case you've missed it: your app is currently [live in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.portscanner.superredstone) which grabs the APK from your releases. It didn't fetch today's update (with this fix included) as there was no APK at the release tag.

**Comment by Superredstone** [comment]
Fixed!

**Comment by IzzySoft** [comment]
Confirmed! Just triggered an update manually, and it pulled 1.0.3 fine. Will show up in my repo with tomorrow's sync. Forgot to enable fastlane pulling, so description etc. was not updated along – will switch that on now so it comes along with the next release. Thanks a lot!

**Comment by Superredstone** [comment]
I thank you too
